# Generated by Django 3.1.2 on 2020-11-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSellerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField()),
                ('price', models.IntegerField(max_length=32)),
                ('modification', models.CharField(blank=True, max_length=128)),
                ('year_manufacture', models.IntegerField(max_length=4)),
                ('mileage', models.IntegerField(max_length=8)),
                ('quantity_owner', models.CharField(max_length=2)),
                ('quantity_doors', models.IntegerField(max_length=2)),
                ('address', models.CharField(max_length=128)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclebodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclebrand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclecolor')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclecondition')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicledrive')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicleenginetype')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicleequipment')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclegeneration')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclemodel')),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclesellertype')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicletransmission')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclewheel')),
            ],
        ),
    ]
