# Generated by Django 3.1.2 on 2020-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle_vehiclebodytype_vehiclebrand_vehiclecolor_vehiclecondition_vehicledrive_vehicleenginetype_ve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='quantity_doors',
            field=models.IntegerField(),
        ),
    ]
