# Generated by Django 3.1.2 on 2020-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201114_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_manufacture',
            field=models.IntegerField(),
        ),
    ]
