# Generated by Django 3.1.2 on 2020-11-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201114_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicleequipment'),
        ),
    ]
