# Generated by Django 3.1.2 on 2021-01-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.region'),
        ),
    ]
