# Generated by Django 3.1.2 on 2021-01-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210120_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.region'),
        ),
    ]
