# Generated by Django 3.1.2 on 2021-01-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210120_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='region',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='seller_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='wheel',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleBodyType',
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleColor',
        ),
        migrations.DeleteModel(
            name='VehicleCondition',
        ),
        migrations.DeleteModel(
            name='VehicleDrive',
        ),
        migrations.DeleteModel(
            name='VehicleEngineType',
        ),
        migrations.DeleteModel(
            name='VehicleEquipment',
        ),
        migrations.DeleteModel(
            name='VehicleGeneration',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.DeleteModel(
            name='VehicleSellerType',
        ),
        migrations.DeleteModel(
            name='VehicleTransmission',
        ),
        migrations.DeleteModel(
            name='VehicleWheel',
        ),
    ]
